
# Intrivial is a time between end of the last event or start of the server
# and start of announcement of the next event.
# Admins can check remaining time with /eventtimer command, players can't check it.
intrivial: 5

# Announcement is the time between the end of the end of intrivial and the start of the next event.
# It is visible to all players via bossbar at the top of the screen.
announcement: 10

# Events configuration
# You can enable or disable events, and set their duration.
events:
  LiquidSwap:
    enabled: false
    time: 300

  YouAreZombie:
    enabled: false
    time: 120

  NoRegeneration:
    enabled: false
    time: 120

  LowGravity:
    enabled: false
    time: 120

  DeadGoBoom:
    enabled: false
    time: 300
    setFire: true
    players: true
    mobs: true

  BePacifist:
    enabled: false
    time: 150

  NoJumping:
    enabled: false
    time: 120

  AdventureTime:
    enabled: false
    time: 90

  WallHack:
    enabled: false
    time: 300

  MoveOrDie:
    enabled: false
    time: 300

  ADHDInventory:
    enabled: true
    time: 120