name: RandomTimedEvents
version: '1.0'
main: me.pinkcandy.randomTimedEvents.RandomTimedEvents
api-version: '1.21'
commands:
  rte:
    description: 'Random timed events control command.'
    usage: 'Wrong usage! Use /rte help for command info.'
    permission: rte
    permission-message: 'You do not have permission to use this command.'